### ISSUE TITLE
Add ability to interpolate variables into commands

### ISSUE THREAD

**Issue by azohra** [azohra/elir#3]
instead of delegating to a bash script, can we instead have this

```
  cmd: bundle exec rspec ${TESTS}
```

**Comment by florinpatrascu** [comment]
started to work on this, but it's a bit trickier than I expected

**Comment by florinpatrascu** [comment]
this: ` cmd: bundle exec rspec ${TESTS}` is now: ` cmd: bundle exec rspec ${elir[:TESTS]}`
